name: memeface
description: A meme face overlapper powered by Google Vision ML & Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  camera: ^0.2.4
  path_provider: ^0.4.1
  firebase_ml_vision: ^0.2.0+2
  image: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - graphics/